name: Go CI

on: 
  pull_request:
    branches: main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v5
      
      - name: Backend - download deps
        working-directory: backend
        run: go mod download

      - name: Backend - build
        working-directory: backend
        run: go build -o backend
      
      - name: Frontend - download deps
        working-directory: frontend
        run: go mod download

      - name: Frontend - build
        working-directory: frontend
        run: go build -o backend

      - name: Frontend -test
        working-directory: frontend
        run: go test 