---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  type: ClusterIP