---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers: 
      - name: backend
        image: itnerddk/simple-fortune-cookie-backend:latest # Change this when image is up
        resources:
          requests:
            cpu: "128Mi"
            memory: "500m"
        ports:
        - containerPort: 9000
      restartPolicy: Always
      imagePullPolicy: Always