---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers: 
      - name: backend
        image: ghcr.io/itnerddk/simple-fortune-cookie-backend:latest
        resources:
          requests:
            cpu: "200m"
            memory: "128Mi"
        ports:
        - containerPort: 9000