---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: database
  name: database-service
spec:
  selector:
    app: database
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  type: ClusterIP