name: CD

on:
  push:
    branches: main

env:
  docker_username: itnerddk
  docker_password: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT: ${{ github.sha }}

jobs:
  Docker-image-frontend:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: build docker
        run: bash ci/build-docker-frontend.sh
      - name: push docker
        run: bash ci/push-docker-frontend.sh
  Docker-image-backend:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: build docker
        run: bash ci/build-docker-backend.sh
      - name: push docker
        run: bash ci/push-docker-backend.sh
  Availability-testing:
    runs-on: ubuntu-latest
    steps:
      - name: curl
        run: scripts/availability-test.sh http://13.62.20.151:"kubectl describe service frontend | grep -i nodeport | awk '{print $3}' | cut -d'/' -f1"/
