name: Go CI

on: 
  pull_request:
    branches: main    

env:
  docker_username: itnerddk
  docker_password: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT: ${{ github.sha }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v5
      
      - name: Backend - download deps
        working-directory: backend
        run: go mod download

      - name: Backend - build
        working-directory: backend
        run: go build -o backend
      
      - name: Frontend - download deps
        working-directory: frontend
        run: go mod download

      - name: Frontend - build
        working-directory: frontend
        run: go build -o backend

      - name: Frontend -test
        working-directory: frontend
        run: go test 
  Docker-image-frontend:
    runs-on: ubuntu-latest
    needs: [build-and-test]
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: build docker
        run: bash ci/build-docker-frontend.sh
      - name: push docker
        run: bash ci/push-docker-frontend.sh
  Docker-image-backend:
    runs-on: ubuntu-latest
    needs: [build-and-test]
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: build docker
        run: bash ci/build-docker-backend.sh
      - name: push docker
        run: bash ci/push-docker-backend.sh